DROP TABLE IF EXISTS europeprices;

CREATE TABLE IF NOT EXISTS europeprices (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    COUNTRY TEXT NOT NULL, 
    GASOLINE TEXT NOT NULL, 
    DIESEL TEXT NOT NULL, 
    LPG TEXT NOT NULL
);
